pipeline {
    agent any

    tools {
        maven 'maven'      // Configure Maven in Jenkins Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Checking out code from SCM"
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                echo "Running Maven Build & Tests"
                dir('AutomationTesting') {
                    sh "mvn clean test"
                }
            }
        }

        stage('Reports') {
            steps {
                junit 'AutomationTesting/target/surefire-reports/*.xml'
                publishHTML([
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'AutomationTesting/target',
                    reportFiles: 'ExtentReport.html',
                    reportName: 'Extent Report'
                ])
            }
        }
    }
}
